name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      python-version: '3.10'
    strategy:
      matrix:
        sphinx: [ 'sphinx==5.3.0', 'sphinx==6.2.1', 'sphinx==7.*' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}

    - name: Set up Sphinx ${{ matrix.sphinx-version }}
      run: |
        python -V
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docs/requirements.txt
        pip install "${{ matrix.sphinx-version }}"

    - name: Tests
      run: |
        python -m sphinx docs/ build/html -b html -D html_theme=alabaster
